### ISSUE TITLE
Can not read property '_importPrivate' of undefined

### ISSUE THREAD

**Issue by zhulduz** [calvinmetcalf/createECDH#9]
Hello guys,

This error I get always, when I try to create a new instance of ECDH class and set private key. 
My code here:

``` coffescript
ecdh = ECDH 'prime256v1'
ecdh.setPrivateKey d
```

Could you please clarify what does parameter 'keys' mean?
The same code I use with node module 'crypto', it works good.

**Comment by fanatid** [comment]
https://github.com/crypto-browserify/createECDH/blob/115f7b6bad56934285b9015575e1b43f23148a8a/browser.js#L103
should be:

``` js
this.keys = this.curve.keyFromPrivate(priv)
```

`.setPublicKey` also affected

ref in elliptic: https://github.com/indutny/elliptic/blob/614d7c43471ea9fa1cb8759d022a491dac129a7a/lib/elliptic/ec/index.js#L44

**Comment by jmendiola222** [comment]
Facing this issue as well, any plan to fix it on future release? Or a work around?

**Comment by nico-bianco** [comment]
Found a work around:
If you generate the keys for the ECDH object before setting your own private key, the ```keys``` object won't be undefined and you won't get this error.

Something like this: 
```
  const ecdh = cryptoService.createECDH('secp256k1');
  ecdh.generateKeys();
  ecdh.setPrivateKey(privateKey);
```

**Comment by kokosro** [comment]
if you are not aware yet, when setting private key:
 ```
const ecdh = cryptoService.createECDH('secp256k1');
  ecdh.generateKeys();
  ecdh.setPrivateKey(privateKey);
```
the public key is not regenerated, it remains the same as the one generated by ecdh.generateKeys();

so the workaround for not getting `Can not read property '_importPrivate' of undefined` error doesn't work if you don't know the both custom private and public key that you want to use.

**Comment by calvinmetcalf** [comment]
@kokosro  I don't believe that is the case, setting private should change both keys, as long as you havn't gotten the public key first

**Comment by calvinmetcalf** [comment]
this should be fixed by #8

**Comment by calvinmetcalf** [comment]
ah ok so here's the deal, prior to node v5 you had to call generateKeys before you could import a private one, that's fixed in newer node and this library had been just following how node worked

**Comment by kokosro** [comment]
is this now available on the latest version on npm ?

**Comment by calvinmetcalf** [comment]
no, it's not merged yet

**Comment by calvinmetcalf** [comment]
published
